Repository LucasFournier-GIT/shoploc-frontend, pull requests merged in 2024-04, with the labels that each got.

#5 feat : update the status of shop following current time
  components/ShopCard.js
Labels: feature

#4 SCRUM-69 feat view, update and delete product
  components/shop/shopComponents/ShopProduct.js
  components/shop/shopScreens/ShopProductsScreen.js
  components/shop/shopScreens/ShopUpdateProduct.js
Labels: feature

#6 feat: ajout visualisation profile et refacto variables d'env
  .env.example
  App.js
  components/CartItem.js
  components/CustomModal.js
  components/CustomNavBar.js
  components/Profile/EditProfileForm.js
  components/screens/CartScreen.js
  components/screens/CreateAccountScreen.js
  components/screens/HomeScreen.js
  components/screens/LoginScreen.js
  components/screens/ProfileScreen.js
  components/screens/RecapCartScreen.js
  components/screens/ShopScreen.js
  components/shop/shopScreens/ShopOrdersScreen.js
  components/shop/shopScreens/ShopUpdateProduct.js
  package-lock.json
  package.json
Labels: feature, configuration

#11 feat: add register form for user
  App.js
  components/CartItem.js
  components/CustomModal.js
  components/ProductCard.js
  components/register/RegisterScreen.js
  components/screens/CartScreen.js
  components/screens/HomeScreen.js
  components/screens/LoginScreen.js
  components/screens/ProfileScreen.js
  components/screens/RouteScreen.js
  components/screens/ShopScreen.js
  components/shop/shopScreens/ShopProductsScreen.js
  components/shop/shopScreens/ShopUpdateProduct.js
  eas.json
  package.json
Labels: feature

#10 Scrum 91 - View orders for a shop
  App.js
  components/ProductCard.js
  components/screens/HomeScreen.js
  components/screens/LoginScreen.js
  components/screens/ShopScreen.js
  components/shop/shopComponents/ShopNavbar.js
  components/shop/shopComponents/ShopOrder.js
  components/shop/shopComponents/ShopProduct.js
  components/shop/shopScreens/ShopOrderDetailsScreen.js
  components/shop/shopScreens/ShopOrdersScreen.js
  components/shop/shopScreens/ShopProductsScreen.js
  components/shop/shopScreens/ShopUpdateProduct.js
  package.json
Labels: feature

#13 fix: style and env variable
  App.js
  assets/backendUrl.js
  components/CartItem.js
  components/ProductCard.js
  components/register/RegisterScreen.js
  components/screens/CartScreen.js
  components/screens/CreateAccountScreen.js
  components/screens/HomeScreen.js
  components/screens/LoginScreen.js
  components/screens/ProfileScreen.js
  components/screens/RouteScreen.js
  components/screens/ShopScreen.js
  components/shop/shopComponents/ShopProduct.js
  components/shop/shopScreens/ShopOrderDetailsScreen.js
  components/shop/shopScreens/ShopOrdersScreen.js
  components/shop/shopScreens/ShopProductsScreen.js
  components/shop/shopScreens/ShopProfileScreen.js
  components/shop/shopScreens/ShopUpdateProduct.js
  components/shop/shopScreens/ShopUpdateProfileScreen.js
Labels: bug, configuration

#12 feat: ajout boutons vers PBI et gestion ville
  App.js
  components/Profile/EditProfileForm.js
  components/city/cityComponents/CityNavbar.js
  components/city/cityScreens/HomeCityscreen.js
  components/city/cityScreens/ProfileCityScreen.js
  components/screens/LoginScreen.js
  components/screens/ProfileScreen.js
Labels: feature

#16 feat: create product from shop ui
  App.js
  components/city/cityScreens/ProfileCityScreen.js
  components/shop/shopScreens/CreateProductScreen.js
  components/shop/shopScreens/ShopOrdersScreen.js
  components/shop/shopScreens/ShopProductsScreen.js
  components/shop/shopScreens/ShopProfileScreen.js
Labels: feature

#20 fix: create shop link to user
  components/city/cityScreens/CreateShopScreen.js
Labels: bug
